# Generated by Django 3.0.1 on 2020-07-24 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRUM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rumform', models.FileField(upload_to='rumform')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRUCF2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f2form', models.FileField(upload_to='f2form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRUCF1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1form', models.FileField(upload_to='f1form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRUCA1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1form', models.FileField(upload_to='a1form')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number_year', models.TextField(max_length=191)),
                ('adm_no', models.TextField(max_length=191)),
                ('student_name', models.TextField(max_length=191)),
                ('box', models.TextField(blank=True, max_length=191, null=True)),
                ('postalcode', models.TextField(blank=True, max_length=191, null=True)),
                ('town', models.TextField(blank=True, max_length=191, null=True)),
                ('school', models.TextField(blank=True, max_length=191, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('joined_date', models.TextField(blank=True, max_length=191, null=True)),
                ('gender', models.TextField(blank=True, max_length=191, null=True)),
                ('salutation', models.TextField(blank=True, max_length=191, null=True)),
                ('religion', models.TextField(blank=True, max_length=191, null=True)),
                ('mstatus', models.TextField(blank=True, max_length=191, null=True)),
                ('phone_number', models.TextField(blank=True, max_length=191, null=True)),
                ('dob', models.TextField(blank=True, max_length=191, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='UserProfiles')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
