# Generated by Django 3.0.1 on 2020-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='adm_no',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='box',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='dob',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='gender',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='index_number_year',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='joined_date',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='mstatus',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='postalcode',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='religion',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='salutation',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='school',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='student_name',
            field=models.CharField(max_length=191),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='town',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
