# Generated by Django 3.1 on 2020-08-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200724_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_name', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postalcode', models.CharField(blank=True, max_length=191, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userregistration',
            name='birth_cert_no',
            field=models.CharField(default='12345678', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='ethinicity',
            field=models.CharField(default='12345678', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='id_passport_no',
            field=models.CharField(default='12345678', max_length=20),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='nationality',
            field=models.CharField(default='12345678', max_length=191),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='physicaly_impaired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=191),
        ),
    ]
