# Generated by Django 3.1 on 2020-08-08 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200808_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='physicaly_impaired_details',
            field=models.TextField(default=False),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='birth_cert_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='ethinicity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='id_passport_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='nationality',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='phone_number',
            field=models.CharField(blank=True, max_length=191, null=True),
        ),
    ]
